GET http://localhost:8080
# Host: www.rust-lang.org

###
GET http://localhost:8080/api/v1/users/ HTTP/1.1
User-Agent: rest-client
Content-Type: application/json

{
  "page":0,
  "take":10,
  "username": "",
  "first_name": "",
  "last_name": "",
  "email": "",
  "active": true,
  "roles": []

}
###
GET http://localhost:8080/api/v1/users/fc1b278b-1a73-446f-b354-8caa36b3c13d HTTP/1.1
User-Agent: rest-client


###

POST http://localhost:8080/api/v1/users/ HTTP/1.1
User-Agent: rest-client
Content-Type: application/json

{
      "username": "user 3",
      "staff_title": "staff",
      "education_title": "Phd",
      "email": "user3@example.com",
      "password": "password",
      "first_name": "user 3",
      "last_name": "loser 3",
      "bio": "some bio 3",
      "image": "",
      "department_id":null,
      "roles": []
}

###

PUT http://localhost:8080/api/v1/users/ HTTP/1.1
User-Agent: rest-client
Content-Type: application/json

{
    "id": "fc1b278b-1a73-446f-b354-8caa36b3c13d",
    "staff_title": "staff",
    "education_title": "Phd",
    "first_name": "user 1",
    "last_name": "loser",
    "bio": "some bio",
    "image": "",
    "department_id": null,
    "roles": [
      "admin"
    ]
  }
  
###

DELETE  http://localhost:8080/api/v1/users/750a7d29-9725-4064-bb12-357fe81c627d HTTP/1.1
User-Agent: rest-client

###
